# Site Settings
title: Topas4 info page
description: >
  Topas4 info page
baseurl: "/Topas4Info"
url: "http://domasm.github.io"
fullUrl: "http://domasm.github.io/Topas4Info"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages', '_nonVisiblePages']
kramdown:
  input: GFM